name: logger_flutter
description: Flutter extension for logger. Based on https://github.com/leisim/logger_flutter
version: 0.9.1+1
author: Dan Osterrath
homepage: https://github.com/dan-osterrath/logger_flutter

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  logger: ">=0.9.1"
  sensors: ^0.4.2+2
  synchronized: 2.2.0+1